# Generated by Django 4.2.5 on 2023-10-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InicioProject', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
